/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "enwnxwqqpmntrdbeztxi"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVud254d3FxcG1udHJkYmV6dHhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEyODE1MDQsImV4cCI6MjA4Njg1NzUwNH0.7--NZthC0w7YS0clzBNEb7jA3j8h6ZBD5H7eeq6BQUQ"